### PR TITLE
Add albumLabel to Options.

### PR DESCRIPTION
**Pull request by reitermarkus**
It took me quite a bit of time to figure out this had already been implemented, as there are multiple requests for this which haven't been closed:

https://github.com/lokesh/lightbox2/issues/113
https://github.com/lokesh/lightbox2/pull/343

### CODE REVIEW

**Comment by reitermarkus** [comment]
Push.

**Comment by reitermarkus** [comment]
@lokesh, can you merge this?

**Comment by reitermarkus** [comment]
Push.

**Comment by lokesh** [comment]
aye, totally missed this. my bad. merging now. Thanks!

**Comment by reitermarkus** [comment]
Finally, thanks! =)

**Pull request merged**
